name: jinja_conduit
description: Jinja Conduit example.
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  jinja: ^0.4.0-0

# dev.
#
# dependency_overrides:
#   jinja:
#     path: ../jinja
